![titanic](img/titanic_historical.jpg "Pintura do Titanic")

# EXERCÍCIOS: Análise de Dados do Titanic

O RMS Titanic foi um navio de passageiros britânico operado pela empresa *White Star Line* que afundou no Oceano Atlântico Norte nas primeiras horas da manhã de 15 de abril de 1912, depois de atingir um iceberg durante sua viagem inaugural de Southampton a Nova York. Dos 2.224 passageiros e tripulantes a bordo, mais de 1.500 morreram, tornando o naufrágio um dos desastres marítimos comerciais mais mortais da história moderna em tempos de paz.

Neste estudo iremos explorar um conjunto de dados baseado na lista de passageiros do Titanic editada por Michael A. Findlay, publicada originalmente em Eaton & Haas (1994) Titanic: Triumph and Tragedy, Patrick Stephens Ltd, e expandida com a ajuda da comunidade da Internet. Os arquivos HTML originais foram obtidos por Philip Hind (1999) e o *dataset* descreve o status de sobrevivência de passageiros individuais no Titanic. Ele não contém informações para a tripulação, mas contém idades atuais e estimadas para quase 80% dos passageiros.

## Dicionário de Dados

Nesta seção será apresentado todo o processo de preparação, organização e limpeza de dados feito no *dataset* que possui os seguintes dados:

| Nº | Coluna          | Descrição                                                                 |
|:--:|:----------------|:--------------------------------------------------------------------------|
|  1 | id_passageiro   | Identficador único do passageiro.                                         |
|  2 | classe          | Classe social.                                                            |
|  3 | sobreviveu      | Sobrevivente? Sim (1), Não (0).                                           |
|  4 | nome            | Nome do passageiro.                                                       |
|  5 | sexo            | Masculino (male), Feminino (female).                                      |
|  6 | idade           | Idade do passageiro.                                                      |
|  7 | irmaos_conjuges | Número de irmãos e cônjuges a bordo.                                      |
|  8 | pais_filhos     | Número de pais e filhos a bordo.                                          |
|  9 | bilhete         | Número do bilhete                                                         |
| 10 | tarifa          | Preço da tarifa do passageiro.                                            |
| 11 | cabine          | Cabine.                                                                   |
| 12 | embarque        | Nome do porto de embarque: C = Cherbourg; Q = Queenstown; S = Southampton |
| 13 | bote            | Bote salva vidas.                                                         |
| 14 | corpo           | Número de identificação do corpo.                                         |
| 15 | destino         | Local de desembarque do passageiro.                                       |

### OBSERVAÇÕES

- `classe` é uma aproximação do status socioeconômico na época, onde: 1 = Classe Alta1; 2 = Classe Média e 3 = Classe Baixa;
- `idade` está representada em anos, porém, se a idade for menor que Um (1) ou caso tenha sido estimada, ela estará com casas decimais xx.5;
- `tarifa` está em Libras esterlinas (British Pounds - £) anteriores a 1970;
- `irmaos_conjuges` e `pais_filhos`: as variáveis de relação familiar de algumas relações foram ignoradas; a seguir estão as definições usadas:
    - **Irmão**: Irmão, irmã, meio-irmão ou meia-irmã do passageiro a bordo do Titanic;
    - **Cônjuge**: Marido ou esposa do passageiro a bordo do Titanic (amantes e noivos ignorados);
    - **Pai**: Mãe ou pai do passageiro a bordo do Titanic;
    - **Criança**: Filho, Filha, Enteado ou Enteada do Passageiro a bordo do Titanic;
    - Outros parentes excluídos deste estudo incluem primos, sobrinhos / sobrinhas, tias / tios e parentes;
    - Algumas crianças viajavam apenas com uma babá, portanto foi atribuído 0 para elas em pais_filhos; 
    - Alguns viajaram com amigos ou vizinhos muito próximos em uma vila, no entanto, as definições não apóiam essas relações.


## Exercícios
Faça as questões abaixo usando somente a biblioteca [Numpy](https://numpy.org/).

1. Importe o pacote numpy com o nome np.

In [21]:
import numpy as np

2. Carregue o conjunto de dados disponível na pasta [data/titanic3.csv](data/titanic3.csv), ignorando as colunas: `cabine`, `bote`, `corpo` e `destino`. **Importante:** o arquivo `.csv` usa tabulação (`\t`) como delimitador de campos.

In [22]:
dados = np.genfromtxt('titanic3.csv', delimiter='\t', encoding='utf-8', dtype=object, skip_header=True, usecols=[0,1,2,3,4,5,6,7,8,9,11])

3. Quantas linhas foram lidas do arquivo?

In [23]:
len(dados)

1309

4. Quantas dimensões sua variável dados possui?

In [24]:
np.ndim(dados)

2

5. Obtenha os índices das posições onde existam dados ausentes.

In [26]:
condicao_vz = dados == b''
remove = np.where(dados == b'')
remove

(array([  15,   37,   40,   46,   59,   69,   70,   74,   80,  106,  107,
         108,  118,  121,  125,  134,  147,  152,  157,  166,  168,  176,
         179,  184,  196,  204,  219,  223,  235,  237,  241,  254,  256,
         269,  277,  283,  284,  293,  297,  318,  320,  363,  382,  384,
         410,  469,  473,  477,  483,  491,  495,  524,  528,  531,  581,
         595,  597,  672,  680,  681,  682,  705,  706,  756,  757,  767,
         768,  775,  789,  795,  798,  800,  801,  802,  804,  805,  808,
         812,  813,  815,  816,  819,  835,  842,  843,  852,  854,  856,
         858,  865,  871,  872,  874,  876,  879,  882,  886,  887,  900,
         901,  902,  903,  918,  920,  921,  922,  923,  926,  927,  928,
         929,  930,  931,  940,  942,  944,  945,  946,  948,  954,  955,
         956,  957,  958,  961,  962,  971,  973,  976,  982,  983,  984,
         987,  988,  989,  991,  993,  994,  997,  998,  999, 1000, 1001,
        1002, 1003, 1004, 1005, 1006, 

6. Remova todas as linhas que possuem dados ausentes.

In [27]:
condicao_vz = dados != b''
novoDados = dados[remove ]

7. Mostre todos os dados das 5 primeiras linhas do dataset.

In [7]:
dados[:5]

array([[b'1', b'1', b'1', b'Allen, Miss. Elisabeth Walton', b'female',
        b'29', b'0', b'0', b'24160', b'211.3375', b'S'],
       [b'2', b'1', b'1', b'Allison, Master. Hudson Trevor', b'male',
        b'1', b'1', b'2', b'113781', b'151.5500', b'S'],
       [b'3', b'1', b'0', b'Allison, Miss. Helen Loraine', b'female',
        b'2', b'1', b'2', b'113781', b'151.5500', b'S'],
       [b'4', b'1', b'0', b'Allison, Mr. Hudson Joshua Creighton',
        b'male', b'30', b'1', b'2', b'113781', b'151.5500', b'S'],
       [b'5', b'1', b'0',
        b'Allison, Mrs. Hudson J C (Bessie Waldo Daniels)', b'female',
        b'25', b'1', b'2', b'113781', b'151.5500', b'S']], dtype=object)

8. Crie as variáveis: `idade`, `irmaos_conjuges`, `pais_filhos` e `tarifa`; com todos os dados dessas colunas, e, tipos de dados conforme a tabela abaixo:

| Nº | Coluna          | Tipo de Dados |
|:--:|-----------------|---------------|
|  6 | idade           | int           |
|  7 | irmaos_conjuges | int           |
|  8 | pais_filhos     | int           |
| 10 | tarifa          | float         |

In [28]:
condicao_vazio = dados[:,5] != b''
idades = np.array(dados[condicao_vazio,5],dtype=int)

condicao_vazio = dados[:,6] != b''
irmaos_conjuges = np.array(dados[condicao_vazio,6],dtype=int)

condicao_vazio = dados[:,7] != b''
pais_filhos = np.array(dados[condicao_vazio,7], dtype=int)

condicao_vazio = dados[:,9] != b''
tarifa = np.array(dados[condicao_vazio,9], dtype=float)


9. Selecione as primeiras 5 linhas dos dados.

In [29]:
print(idades[:5])
print(irmaos_conjuges[:5])
print(pais_filhos[:5])
print(tarifa[:5])

[29  1  2 30 25]
[0 1 1 1 1]
[0 2 2 2 2]
[211.3375 151.55   151.55   151.55   151.55  ]


10. Considerando o vetor `idades`, selecione todas as idades das crianças a bordo menores de 12 anos inclusive.

In [10]:
menor_idade = 12
condicao = idades <= menor_idade

idades[condicao]

array([ 1,  2, 11,  4,  6,  1,  4, 12,  1,  8,  8,  8,  1,  6,  7,  1,  3,
        1,  2,  3,  2,  8,  1,  3, 12,  2,  4,  1,  5,  1,  4,  6,  2,  9,
       11,  5,  9,  3,  5,  1,  1,  5,  6,  9,  9,  3,  0,  1,  0,  5,  9,
        9,  9,  1, 11, 10, 11,  2,  4,  1,  4,  4,  1,  6,  1, 12,  9,  2,
        6,  3,  8,  1,  7,  2,  1,  3, 10,  4,  7,  2,  8,  2,  1,  4,  4,
       10,  9,  2,  2,  0,  7,  9, 12, 10])

11. Qual é a média das idades?

In [11]:
idades.mean()

29.89770554493308

12. Quais é a maior e menor idade?

In [12]:
idades.min()

0

13. Crie um vetor chamado `sobreviventes` com todos os dados das pessoas que sobreviveram ao naufrágio.

In [15]:
condicao_vz = dados[:,2] != b''
sobreviventes = np.array(dados[condicao_vazio,2], dtype=int)

14. Segundo este conjunto de dados, quantas pessoas sobreviveram ao naufrágio?

In [16]:
condicao = sobreviventes == 1
sobreviveu = sobreviventes[condicao]
len(sobreviveu)

500

15.  Considerando a coluna `idade` dos sobreviventes calcule:
    - Média
    - Mediana
    - Máximo
    - Mínimo

In [ ]:
print(idades.mean())
print(np.median(idades))
print(idades.max())
print(idades.min())

16. Crie um vetor chamado `vitimas_naufragio` com todos os dados das pessoas que não sobreviveram ao naufrágio.

In [17]:
condicao = sobreviventes == 0
novoDado = sobreviventes[condicao]
vitimas_naufragio = dados[novoDado]

array([[b'1', b'1', b'1', ..., b'24160', b'211.3375', b'S'],
       [b'1', b'1', b'1', ..., b'24160', b'211.3375', b'S'],
       [b'1', b'1', b'1', ..., b'24160', b'211.3375', b'S'],
       ...,
       [b'1', b'1', b'1', ..., b'24160', b'211.3375', b'S'],
       [b'1', b'1', b'1', ..., b'24160', b'211.3375', b'S'],
       [b'1', b'1', b'1', ..., b'24160', b'211.3375', b'S']], dtype=object)

17. Considerando a coluna `vitimas_naufragio` dos sobreviventes calcule:
    - Média
    - Mediana
    - Máximo
    - Mínimo

18. Qual era o preço médio das tarifas?

In [ ]:
tarifa.mean()

19. Crie os vetores `classe_alta`, `classe_media` e `classe_baixa`, com os respectivos dados da coluna `classe` no qual:
    - 1 = Classe Alta
    - 2 = Classe Média
    - 3 = Classe Baixa

In [ ]:

condicao = dados[:,1] == b'1'
classe_alta = np.array(dados[condicao,1], dtype=int)
print(len(classe_alta))


condicao = dados[:,1] == b'2'
classe_media = np.array(dados[condicao,1], dtype=int)
print(len(classe_media))


condicao = dados[:,1] == b'3'
classe_baixa = np.array(dados[condicao,1], dtype=int)
print(len(classe_baixa))

20. Qual é o número total de passageiros por classe social?

# REFERÊNCIAS

- [Titanic: Machine Learning from Disaster](https://www.kaggle.com/c/titanic/data)
- [Encyclopedia Titanica](https://www.encyclopedia-titanica.org/)
- [Basic Feature Engineering with the Titanic Data](https://triangleinequality.wordpress.com/2013/09/08/basic-feature-engineering-with-the-titanic-data/)
- Hind, Philip.  "Encyclopedia Titanica."  Online.  Internet. n.p.  02 Aug 1999.